defaults: &defaults
  working_directory: ~/reg-suit
  docker:
    - image: node:6

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Bootstrap packages
          command: yarn run lerna -- bootstrap
      - run:
          name: Lint
          command: yarn run lint
      - run:
          name: Test
          command: yarn run test
  deploy:
    <<: *defaults
    steps:
      - add-ssh-keys:
          fingerprints:
            - "9b:4a:d1:c6:ff:b7:49:b7:b7:bf:24:fb:b1:1e:bc:a6"
      - checkout
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Bootstrap packages
          command: yarn run lerna -- bootstrap
      - run:
          name: Setup git
          command: |
            git config --global user.email "yosuke.kurami@gmail.com"
            git config --global user.name "Quramy"
      - run:
          name: Login npm
          command: |
            echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" > ~/.npmrc
            npm whoami
      - run:
          name: Publish to npm
          command: |
            echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" > ~/.npmrc
            yarn run lerna publish -- --yes --cd-version="patch"

workflows:
  version: 2
  publish_npm:
    jobs:
      - build
      - hold:
          type: approval
          filters:
            branches:
              only: master
          requires:
            - build
      - deploy:
          filters:
            branches:
              only: master
          requires:
            - hold

